title: "#0xda"
description: "Cybersecurity blog - place where cybersecurity is all about ethics and professionalism"
author:
  name: "Giulio Astori - #0xda"
  email: "g.astori@outlook.com"
  url: "https://gastori.github.io"

baseurl: /

source: .
destination: ./_site
permalink: /:title
paginate: 5
paginate_path: /page/:num/

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

future: true
plugins:
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-sitemap

# Custom variables
owner : "#0xda Giulio Astori"
year : "2021"
google_analytics: "UA-189824580-1"
